default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hnc_scholar_scores_development

test:
  <<: *default
  database: hnc_scholar_scores_test

production:
  <<: *default
  database: hnc_scholar_scores_production
  username: geoff
  password: <%= ENV['HNC_SCHOLAR_SCORES_DATABASE_PASSWORD'] %>
